{% set name = "jax-finufft" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jax-finufft/jax_finufft-{{ version }}.tar.gz
  sha256: 0c9173837fa0ae47b61074f8c05b246d9ca5b21bda6174beda8c27ea75c4f152

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: True  # [win or py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - scikit-build-core                      # [build_platform != target_platform]
    - setuptools_scm                         # [build_platform != target_platform]
    - nanobind                               # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [linux]
  host:
    - python
    - scikit-build-core
    - setuptools_scm
    - nanobind
    - pip
    - fftw
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - python
    - jax
    - pydantic

test:
  imports:
    - jax_finufft
    - jax_finufft.jax_finufft_cpu
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/flatironinstitute/jax-finufft
  license: Apache-2.0
  license_file:
    - LICENSE
    - vendor/finufft/LICENSE
  summary: JAX bindings to the Flatiron Institute Non-uniform Fast Fourier Transform library
  dev_url: https://github.com/flatironinstitute/jax-finufft

extra:
  recipe-maintainers:
    - dfm
    - lgarrison
